name: Goodreads Scraper

on:
  schedule:
    # Runs every day at 06:00 UTC (1:00 PM in your local WIB time)
    - cron: "0 6 * * *"
  workflow_dispatch:
    # Allows you to run this workflow manually from the Actions tab

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 supabase-py python-dotenv
          
      - name: Run scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          # The name here MUST match what your Python script expects
          GOODREADS_COOKIES_JSON: ${{ secrets.GOODREADS_COOKIES_JSON }}
        run: python scrape.py
